- hosts: servers
  tasks:
    - name: Update cache 
      apt:
       update_cache: yes
         
    - name: Upgrade all packages on servers
      apt: 
        name: "*"
        state: latest

    - name: upgrade Alpine
       apk: 
          upgrade: yes
          update_cache: yes
        register: result
