- hosts: apt
  tasks:
    - name: Update cache 
      apt:
       update_cache: yes
         
    - name: Upgrade all packages on servers
      apt: 
        name: "*"
        state: latest

- hosts: yum
  tasks:
    - name: DNF update the system
      dnf:
       name:  "*"
       state: latest


- hosts: apk
  tasks:
    - name: Update Alpine packages cache
      community.general.apk:
          update_cache: true
    - name: Upgrade Alpine Linux packages now
      community.general.apk:
          upgrade: yes

