- hosts: apt
  tasks:
    - name: Update cache on Debian and Ubuntu Servers
      apt:
       update_cache: yes
         
    - name: Upgrade all packages on Debian and Ubuntu servers
      apt: 
        name: "*"
        state: latest

- hosts: yum
  tasks:
    - name: Update and upgrade packages in Alma Linux Servers.
      dnf:
       name:  "*"
       state: latest


- hosts: apk
  tasks:
    - name: Update cache in Alpine Linux Servers
      community.general.apk:
          update_cache: true
    - name: Upgrade Alpine Linux packages.
      community.general.apk:
          upgrade: yes

