- hosts: apt
  tasks:
    - name: Update cache 
      apt:
       update_cache: yes
         
    - name: Upgrade all packages on servers
      apt: 
        name: "*"
        state: latest

- hosts: dnf
  tasks:
    - name: DNF update the system
      dnf:
       name:  "*"
       state: latest

